/* Browser port of app/brain.py. Keep formulas and thresholds identical. */
window.ZeroBrain=(()=>{const BTC_ACTIVE_THRESHOLD=.30,RM_DEADZONE=.10,BTC_LINK_MIN_HISTORY=30,EXPANSION_EPSILON=.0001;
function pctChange(current,previous){if(current==null||previous==null||previous===0)return null;return((current-previous)/previous)*100}
function rollingPct(closes,current,minutes){if(current==null||closes.length<=minutes)return null;return pctChange(current,closes[closes.length-minutes-1][1])}
function oneMinuteReturns(closes,count=BTC_LINK_MIN_HISTORY){if(closes.length<count+1)return null;const recent=closes.slice(-(count+1)),returns=[];for(let i=1;i<recent.length;i++){const value=pctChange(recent[i][1],recent[i-1][1]);if(value==null)return null;returns.push(value)}return returns}
function relativeMoveVsBtc(btc15m,coin15m){if(btc15m==null||coin15m==null||Math.abs(btc15m)<RM_DEADZONE)return null;return(btc15m>0?1:-1)*(coin15m-btc15m)}
function btcLinkDetails(btcReturns,coinReturns){if(!btcReturns?.length||!coinReturns?.length)return emptyLink();const count=Math.min(btcReturns.length,coinReturns.length);if(count<BTC_LINK_MIN_HISTORY)return emptyLink();const btc=btcReturns.slice(-count),coin=coinReturns.slice(-count),correlation=pearson(btc,coin);if(correlation==null)return emptyLink();let sameDirection=0;for(let i=0;i<count;i++){if(btc[i]===0||coin[i]===0)continue;if((btc[i]>0&&coin[i]>0)||(btc[i]<0&&coin[i]<0))sameDirection++}const sameDirectionRatio=sameDirection/count,directionScore=(sameDirectionRatio*2-1)*100,correlationScore=correlation*100,score=.75*correlationScore+.25*directionScore;return{score:Math.round(Math.max(-100,Math.min(100,score))),correlation_score:correlationScore,direction_score:directionScore,same_direction_ratio:sameDirectionRatio}}
function btcLink(a,b){return btcLinkDetails(a,b).score}
function expansionDetails(current15m,completed15mCloses){if(current15m==null)return expansionResult('—',null,null,current15m);const previousMoves=completed15mMoves(completed15mCloses);if(previousMoves.length<20)return expansionResult('WARMING',null,null,current15m);const medianMove=median(previousMoves.slice(-20));if(medianMove<=EXPANSION_EPSILON)return expansionResult('WARMING',null,medianMove,current15m);const currentAbs=Math.abs(current15m),ratio=currentAbs/medianMove,direction=directionArrow(current15m);if(ratio>4&&currentAbs>=.80)return expansionResult(`SPIKE ${direction}`,ratio,medianMove,current15m);if(ratio>=2.5&&currentAbs>=.50)return expansionResult(`STRONG ${direction}`,ratio,medianMove,current15m);if(ratio>=1.5&&currentAbs>=.30)return expansionResult(`EXPANDING ${direction}`,ratio,medianMove,current15m);if(ratio>=1)return expansionResult(`BUILDING ${direction}`,ratio,medianMove,current15m);return expansionResult('NORMAL',ratio,medianMove,current15m)}
function expansion(current15m,closes){const d=expansionDetails(current15m,closes);return[d.label,d.ratio]}
function stateLabel(btc15m,coin15m,rmValue,btcLinkValue,expansionLabel){if(btc15m==null||coin15m==null||coin15m===0)return'—';const direction=directionArrow(coin15m),coinAbs=Math.abs(coin15m),btcAbs=Math.abs(btc15m),btcActive=btcAbs>=BTC_ACTIVE_THRESHOLD,sameDirection=(btc15m>0&&coin15m>0)||(btc15m<0&&coin15m<0),oppositeDirection=(btc15m>0&&coin15m<0)||(btc15m<0&&coin15m>0),expansionActive=['EXPANDING','STRONG','SPIKE'].includes(expansionLevel(expansionLabel));if(btcActive&&oppositeDirection&&(coinAbs>=.30||expansionActive))return`DIVERGING ${direction}`;if(btcLinkValue!=null&&btcLinkValue<45&&expansionActive)return`INDEPENDENT ${direction}`;if(!btcActive||!sameDirection||btcLinkValue==null||btcLinkValue<45||btcAbs===0)return'—';const responseRatio=coinAbs/btcAbs;if(responseRatio>=1.5&&rmValue!=null&&rmValue>=.20)return`LEADER ${direction}`;if(responseRatio>=.75&&responseRatio<1.5)return`FOLLOWER ${direction}`;if(responseRatio<.75)return`LAGGARD ${direction}`;return'—'}
function expansionLevel(label){return label&&label!=='—'?label.split(' ',1)[0]:'—'}function stateType(label){return!label||label==='—'||label==='NO SIGNAL'?(label||'—'):label.split(' ',1)[0]}function stateDirection(label){return label.includes('↑')?'up':label.includes('↓')?'down':''}function stateRank(label){return({LEADER:5,DIVERGING:4,INDEPENDENT:3,FOLLOWER:2,LAGGARD:1,'NO SIGNAL':0,'—':-1})[stateType(label)]??-1}function formatPct(value){return value==null?'—':`${value>=0?'+':''}${value.toFixed(2)}%`}function formatExpansion(label,ratio){return ratio==null||['—','WARMING','NORMAL'].includes(label)?label:`${label} ${ratio.toFixed(1)}×`}
function emptyLink(){return{score:null,correlation_score:null,direction_score:null,same_direction_ratio:null}}function expansionResult(label,ratio,medianMove,current15m){return{label,level:expansionLevel(label),direction:current15m>0?'up':current15m<0?'down':'',ratio,median_move:medianMove,current_15m_abs:current15m==null?null:Math.abs(current15m)}}function completed15mMoves(closes){const moves=[];for(let i=1;i<closes.length;i++){const value=pctChange(closes[i][1],closes[i-1][1]);if(value!=null)moves.push(Math.abs(value))}return moves}function median(values){const a=[...values].sort((x,y)=>x-y),n=a.length;return n%2?a[(n-1)/2]:(a[n/2-1]+a[n/2])/2}function pearson(left,right){if(left.length!==right.length||left.length<2)return null;const ml=left.reduce((a,b)=>a+b,0)/left.length,mr=right.reduce((a,b)=>a+b,0)/right.length;let numerator=0,lv=0,rv=0;for(let i=0;i<left.length;i++){const a=left[i]-ml,b=right[i]-mr;numerator+=a*b;lv+=a*a;rv+=b*b}const denominator=Math.sqrt(lv*rv);return denominator===0?null:numerator/denominator}function directionArrow(value){return value>0?'↑':'↓'}return{pctChange,rollingPct,oneMinuteReturns,relativeMoveVsBtc,btcLinkDetails,btcLink,expansionDetails,expansion,stateLabel,expansionLevel,stateType,stateDirection,stateRank,formatPct,formatExpansion}})();
